name: desafio_target
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.3
  flutter_mobx: ^2.2.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  icons_launcher: ^2.1.6
  json_serializable: ^6.7.1
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
  generate: false

  assets:
    - assets/images/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 600
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 800
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 500
